using UnityEngine;

public class FallDetector : MonoBehaviour
{
    [Header("Settings")]
    public float fallLimitY = -5f; // ÙˆÙ‚ØªÛŒ Y Ù¾Ù„ÛŒØ± Ø§Ø² Ø§ÛŒÙ† Ù…Ù‚Ø¯Ø§Ø± Ù¾Ø§ÛŒÛŒÙ†â€ŒØªØ± Ø¨Ø±Ù‡ â†’ Game Over

    private Transform player;
    private GameManageer gameManager;
    private bool hasDied = false;

    void Start()
    {
        player = GameObject.FindGameObjectWithTag("Player").transform;
        gameManager = FindObjectOfType<GameManageer>();
    }

    void Update()
    {
        if (player != null && !hasDied && player.position.y < fallLimitY)
        {
            hasDied = true;
            Debug.Log("ðŸ’€ Ù¾Ù„ÛŒØ± Ø§ÙØªØ§Ø¯ Ù¾Ø§ÛŒÛŒÙ†!");
            gameManager.GameOver();
        }
    }
}
